In [14]:
import numpy as np
import pandas as pd

import os
lista = []

for dirname, _, filenames in os.walk('archive (11)'):
  for filename in filenames:
    lista.append(os.path.join(dirname, filename))

In [15]:
dfs = [pd.read_csv(item) for item in lista]
df = pd.concat(dfs)

In [16]:
df = df[[
    'Year', 'Script Type', 'Rotten Tomatoes  critics', 'Metacritic  critics', 
    'Average audience ', 'Worldwide Gross ($million)', 'Budget ($million)', 'Primary Genre']]

In [17]:
col = df.columns.get_loc('Script Type')

df['Script Type'] = df['Script Type'].fillna('unknown')
for i in range(len(df)):
    value = df.iloc[i, col]

    if 'original screenplay' in value:
            value = 'original'
    elif 'sequel' in value:
        value = 'sequel'
    elif 'true story' in value or 'documentary' in value:
        value = 'real'
    elif 'adaptation' in value:
        value = 'adaptation'
    elif 'remake' in value:
        value = 'remake'
    elif 'prequel' in value:
        value = 'prequel'
    else:
        value = 'unknow'

    df.iloc[i, col] = value

df['Script Type'].unique()

array(['adaptation', 'remake', 'original', 'sequel', 'real', 'prequel',
       'unknow'], dtype=object)

In [18]:
column = 'Worldwide Gross ($million)'
col = df.columns.get_loc(column)
df = df[ df[column] != "-"]

for i in range(len(df)):
    value = df.iloc[i,  col]
    text = str(value)
    text = text.replace(',', '')
    value = float(text)
    df.iloc[i, col] = value

In [19]:
column = 'Rotten Tomatoes  critics'

df = df[df[column] != '-']
df[column].dropna(inplace=True)

col = df.columns.get_loc(column)
df[column] = pd.to_numeric(df[column])

df[column].unique()

array([ 60.,  88.,  50.,  54.,  14.,  26.,  80.,  52.,  71.,  69.,  82.,
         1.,  67.,  27.,  93.,   2.,  23.,  35.,  28.,   3.,  92.,   4.,
        15.,  45.,  13.,  43.,  94.,  91.,   8.,  79.,  66.,  90.,  56.,
        36.,  63.,  49.,  31.,  29.,  95.,  39.,   9.,  70.,  21.,  11.,
        97.,  20.,  18.,  47.,  42.,  61.,  87.,  78.,  86.,  41.,  30.,
        19.,  72.,  33.,  57.,  46.,  55.,  89.,  75.,  96.,  64.,  77.,
        73.,  40.,  38.,  83.,  16.,  51.,  25.,  58.,  53.,  62.,   7.,
        34.,  24.,  32.,  48.,   5.,  85.,  65.,  68.,  22.,  37.,   0.,
        81.,  59.,  44.,  98.,  84.,  12.,  74.,  17.,   6.,  99.,  10.,
        76.,  nan, 100.])

In [20]:
column = 'Metacritic  critics'

df = df[df[column] != '-']
df[column].dropna(inplace=True)

col = df.columns.get_loc(column)
df[column] = pd.to_numeric(df[column])

df[column].unique()

array([ 51,  76,  53,  56,  29,  39,  54,  59,  64,  69,  13,  62,  33,
        75,  17,  37,  45,  35,  19,  77,  81,  47,  28,  46,  65,  73,
        85,  25,  61,  82,  48,  42,  91,  50,  27,  96,  44,  36,  49,
        58,  74,  83,  67,  32,  80,  92,  41,  63,  78,  94,  84,  86,
        79,  70,  31,  34,  40,  71,  43,  55,  57,  24,  26,  66,  30,
        72,  52,   9,  60,  68,  15,  20,  88,  38,  23,  21,  95,  22,
        18,  90,  89,  87,  97,  11, 100,  12,  16,  93,  99,  14],
      dtype=int64)

In [21]:
column = 'Average audience '

df = df[df[column] != '-'].copy()
df[column].dropna(inplace=True)

col = df.columns.get_loc(column)
df[column] = pd.to_numeric(df[column])

df[column].unique()

array([80. , 61. , 78. , 38. , 60. , 81. , 59. , 57. , 69. , 71. , 29. ,
       79. , 24. , 82. , 25. , 50. , 58. , 43. , 49. , 84. , 35. , 45. ,
       70. , 53. , 86. , 75. , 74. , 56. , 76. , 62. , 64. , 48. , 42. ,
       67. , 87. , 72. , 83. , 68. , 66. , 44. , 77. , 89. , 65. , 63. ,
       55. , 93. , 46. , 40. , 51. , 73. , 52. , 39. , 41. , 54. , 88. ,
       30. , 47. , 22. , 85. , 31. , 36. , 91. , 90. , 33. , 27. , 32. ,
       34. , 92. , 37. , 23. ,  7. , 66.5, 90.5, 85.5, 64.5, 77.5, 74.5,
       59.5, 79.5, 55.5, 63.5, 48.5, 69.5, 82.5, 73.5, 58.5, 40.5, 57.5,
       41.5, 72.5, 54.5, 47.5, 62.5, 80.5, 65.5, 67.5, 70.5, 75.5, 32.5,
       56.5, 81.5, 71.5, 33.5, 76.5, 86.5, 15.5, 52.5, 78.5, 46.5, 18.5,
       60.5, 51.5, 43.5, 61.5, 28. , 19. ,  nan])

In [22]:
column = 'Primary Genre'
df[column] = df[column].fillna('unknown')
df[column].value_counts()

Primary Genre
unknown      1678
action         64
drama          47
comedy         37
adventure      24
thriller       19
horror         18
crime          12
biography       7
animation       6
romance         6
musical         3
fantasy         3
sci-fi          2
western         1
mystery         1
Name: count, dtype: int64

In [23]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder() # transform letters to numbers
df['Primary Genre'] = le.fit_transform(df['Primary Genre']) 
df['Script Type'] = le.fit_transform(df['Script Type'])
df

Year  Script Type  Rotten Tomatoes  critics  Metacritic  critics  \
0   2007            0                      60.0                   51   
1   2007            4                      88.0                   76   
2   2007            0                      50.0                   53   
3   2007            1                      54.0                   56   
4   2007            5                      14.0                   29   
..   ...          ...                       ...                  ...   
87  2022            6                      41.0                   45   
88  2022            6                      81.0                   65   
89  2022            6                      73.0                   55   
90  2022            6                      35.0                   43   
91  2022            6                      94.0                   79   

    Average audience  Worldwide Gross ($million) Budget ($million)  \
0                80.0                      456.0                65   
1                80.0                       70.0                50   
2                61.0                       75.0                32   
3                78.0                       29.0                45   
4                38.0                      129.0                40   
..                ...                        ...               ...   
87               76.0                      400.7             120.0   
88               75.0                        4.4                 -   
89               77.0                       76.6              20.0   
90               81.0                      136.5              24.0   
91               71.0                       15.1               1.0   

    Primary Genre  
0               0  
1              15  
2               8  
3               9  
4              12  
..            ...  
87              0  
88              4  
89              0  
90             11  
91              8  

[1928 rows x 8 columns]

In [24]:
df.boxplot(column = ['Metacritic  critics', 'Average audience ', 'Rotten Tomatoes  critics'])

<Axes: >

In [25]:
df[ df['Worldwide Gross ($million)'] < 2000].plot.scatter(x = 'Rotten Tomatoes  critics', y = 'Worldwide Gross ($million)', s = 3)

<Axes: xlabel='Rotten Tomatoes  critics', ylabel='Worldwide Gross ($million)'>

In [26]:
df.describe()

Year  Script Type  Rotten Tomatoes  critics  \
count  1928.000000  1928.000000               1927.000000   
mean   2014.190871     2.040975                 55.782045   
std       4.379729     2.115473                 27.222197   
min    2007.000000     0.000000                  0.000000   
25%    2010.000000     0.000000                 32.000000   
50%    2014.000000     1.000000                 57.000000   
75%    2018.000000     4.000000                 81.000000   
max    2022.000000     6.000000                100.000000   

       Metacritic  critics  Average audience   Primary Genre  
count          1928.000000        1927.000000    1928.000000  
mean             54.600104          63.861702      12.755705  
std              17.089233          14.516398       3.527190  
min               9.000000           7.000000       0.000000  
25%              42.000000          54.000000      14.000000  
50%              54.000000          65.000000      14.000000  
75%              66.000000          75.000000      14.000000  
max             100.000000          93.000000      15.000000